import Config

# Configure your database
config :erp, Erp.Repo,
  database: System.get_env("ORACLE_DATABASE"),
  username: System.get_env("ORACLE_USERNAME"),
  password: System.get_env("ORACLE_PASSWORD"),
  hostname: System.get_env("ORACLE_HOST"),
  port: System.get_env("ORACLE_PORT")
  #pool_size: 5,


  # ==== from tutorial ======
# config :erp, ErpWeb.Endpoint,
#  http: [port:4000],
#  debug_errors: true,
#  code_reloader: true,
#  check_origin: false,
#  watchers: [
#   node: [
#    "node_modules/webpack/bin/webpack.js",
#    "--mode",
#    "development",
#    "--watch-stdin",
#    cd: Path.expand("../assets", __DIR__)
#  ]
# ]



config :erp, ErpWeb.Endpoint,
  # http: [ip: {127, 0, 0, 1}, port: 4000],
  http: [ip: {192,168,64,62}, port: 4000],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base: "I0dPoStx8Inmhxr3Od06JPb+wPOckGhTmCWhkgcqW9bIbKsxCUJMyJQ5hDiMU7Bg",
  watchers: [
    # Start the esbuild watcher by calling Esbuild.install_and_run(:default, args)
    esbuild: {Esbuild, :install_and_run, [:default, ~w(--sourcemap=inline --watch)]}
  ]

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Note that this task requires Erlang/OTP 20 or later.
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Watch static and templates for browser reloading.
config :erp, ErpWeb.Endpoint,
  live_reload: [
    patterns: [
      ~r"priv/static/.*(js|css|png|jpeg|jpg|gif|svg)$",
      ~r"priv/gettext/.*(po)$",
      ~r"lib/erp_web/(live|views)/.*(ex)$",
      ~r"lib/erp_web/templates/.*(eex)$"
    ]
  ]

# Do not include metadata nor timestamps in development logs
config :logger, :console, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime
